### ISSUE TITLE
User profile pages. Edit own user details page

### ISSUE THREAD

**Issue by peterkapena** [peterkapena/literatures#16]
- add profile edit page
- add a new db model for holding profile details
- name and cell number profile image fields
- implement saving of these fields

**Comment by peterkapena** [comment]
name and cell number edit fields

**Comment by andreKiona** [comment]
Added the user profile page, request for the demo session and more advise

**Comment by peterkapena** [comment]
@andreKiona 
Please schedule a session for tomorrow

**Comment by peterkapena** [comment]
I have updated the UI in the master branch. please pull latest from this branch when working on this. otherwise your changes may not work anymore

**Comment by andreKiona** [comment]
Implemented new user interface UI, link the home button to the home page, link the Make an order button to it respective page
And the My profile button to the user edit page as well.

**Comment by peterkapena** [comment]
@andreKiona As important as it is to follow the my previous comment, please use the new changes that have been done in the master branch and work from there. Please focus only what you have been assigned to implement. 

- This issue is tasked for implementing a user profile page. On this user profile page, as stated above at the top, there should be additional fields of name and cell number as well as the existing ones of email address. Do not add anything such as birthdate or whatsoever that has not been mentioned. I understand that we dont have a specific design to follow, but for any design you come up with, please stick to these two additional fields only.
- As far as you may go, you can focus on the front end only unless you deem able to implement the backend you can do so. But it is not a requirement.

So, please delete your branch, make a new one using the latest changes made in the master branch and implement this user profile from there onward. 

Regards

**Comment by andreKiona** [comment]
Updated the user profile as mentioned above. please check it out and advise

**Comment by peterkapena** [comment]
Next:

- implement form validation
- implement back end process

**Comment by andreKiona** [comment]
Noted. We can set up a meeting in the eve if you are available.

**Comment by andreKiona** [comment]
helped is needed for the backend implementation

**Comment by peterkapena** [comment]
@andreKiona  Hi 

I have implemented :

1. add a new db model for holding profile details
2. implement saving of these fields

Please have a look and let me know. You can schedule a session for tonight to discuss further.

Thanks!

**Comment by andreKiona** [comment]
Hi, 

Yes, all seem alright. I have booked a session for tonight 
All seem to be in order for this issue.
