### ISSUE TITLE
Remove card view and add table like view

### ISSUE THREAD

**Issue by peterkapena** [peterkapena/literatures#6]
- Andre to implement
- from the edit page, implement the delete

**Comment by peterkapena** [comment]
https://github.com/peterkapena/oauth2_spa/blob/master/src/components/ClientTable.tsx
Refer to the above list component on how it is listing its item and implement the same on the OrderTable component. Point of reference for cloning can be the react opening and closing fragment.

https://mui.com/joy-ui/react-list/

**Comment by andreKiona** [comment]
Task completed. To be checked before uploading to GitHub

**Comment by peterkapena** [comment]
![Image](https://github.com/peterkapena/literatures/assets/40431787/adae4be9-8f65-4116-b6f3-24a1be362d05)

**Comment by peterkapena** [comment]
@andreKiona  please view the above design that should be implemented in the order table.

**Comment by peterkapena** [comment]
![Image](https://github.com/peterkapena/literatures/assets/40431787/c4c72b4c-3d41-4ec8-b623-420a18d8fcbe)

**Comment by peterkapena** [comment]
when a click is done on the item it should go onto the edit page. from the edit page, implement the delete
