### ISSUE TITLE
Add confirm password field on sign up page

### ISSUE THREAD

**Issue by peterkapena** [peterkapena/literatures#9]

**Comment by andreKiona** [comment]
Need help on checking whether the implication is correct before uploading on GitHub

**Comment by peterkapena** [comment]
This is not working. I can submit the credentials even when I have not typed in the confirmation email.
If you need help, please set up a meeting in google meet using peterkapenapeter@gmail.com

**Comment by peterkapena** [comment]
Mehdi to test password confirm is working as intended

**Comment by andreKiona** [comment]
Successfully tested as advised above. all works fine.
